\doxysection{/\+Users/thibault/kdrive/1-\/\+PROJECTS/\+P-\/42/push\+\_\+swap/push\+\_\+swap\+\_\+visualizer/build/\+\_\+deps/catch2-\/src/include/internal/catch\+\_\+config\+\_\+uncaught\+\_\+exceptions.hpp File Reference}
\hypertarget{catch__config__uncaught__exceptions_8hpp}{}\label{catch__config__uncaught__exceptions_8hpp}\index{/Users/thibault/kdrive/1-\/PROJECTS/P-\/42/push\_swap/push\_swap\_visualizer/build/\_deps/catch2-\/src/include/internal/catch\_config\_uncaught\_exceptions.hpp@{/Users/thibault/kdrive/1-\/PROJECTS/P-\/42/push\_swap/push\_swap\_visualizer/build/\_deps/catch2-\/src/include/internal/catch\_config\_uncaught\_exceptions.hpp}}
{\ttfamily \#include $<$exception$>$}\newline


\doxysubsection{Detailed Description}
Wrapper for UNCAUGHT\+\_\+\+EXCEPTIONS configuration option

For some functionality, Catch2 requires to know whether there is an active exception. Because {\ttfamily std\+::uncaught\+\_\+exception} is deprecated in C++17, we want to use {\ttfamily std\+::uncaught\+\_\+exceptions} if possible. 